name: ARM64

on:
  # run every day of the week at 02:00
  schedule:
    - cron: 0 2 * * *
  workflow_dispatch:

jobs:
 build-arm64-docker:
  name: Build for ARM64 on Docker
  runs-on: ubuntu-24.04-arm
  steps:
    - name: Check Docker and Docker Compose versions
      run: |
        docker --version
        docker compose version
        
    - uses: actions/checkout@v2

    - name: ARM64 build
      run: |
        docker build -t htm-arm64-docker --build-arg arch=arm64 .

    - name: Tests
      run: |
        docker run htm-arm64-docker python htm_test.py

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and push Docker image
      run: |
        docker tag htm-arm64-docker ghcr.io/${{ github.repository }}/htm-arm64:latest
        docker tag htm-arm64-docker ghcr.io/${{ github.repository }}/htm-arm64:${{ github.run_number }}
        docker tag htm-arm64-docker ghcr.io/${{ github.repository }}/htm-arm64:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/htm-arm64:latest
        docker push ghcr.io/${{ github.repository }}/htm-arm64:${{ github.run_number }}
        docker push ghcr.io/${{ github.repository }}/htm-arm64:${{ github.sha }}
